db:
    type: mariadb:10.6
    disk: 2048
cacheredis:
    type: redis:7.0
    configuration:
        maxmemory_policy: volatile-lfu
# comment if you want to disable rabbitmq
rabbitmq:
    type: rabbitmq:3.8
    disk: 1024

# uncomment if you want to use opensearch
#opensearch:
#    type: opensearch:1.2
#    disk: 256

# Change the disk space according to your needs for a.o. media files
fileshare:
    type: network-storage:2.0
    disk: 4096
