db:
    type: mariadb:10.5
    disk: 2048

cacheredis:
    type: redis:6.0

# uncomment if you want to use elasticsearch
# searchelastic:
#     type: elasticsearch:7.9
#     disk: 256

# uncomment if you want to use rabbitmq
# queuerabbit:
#     type: rabbitmq:3.8
#     disk: 1024