parameters:
    env(MESSENGER_TRANSPORT_DSN): "enqueue://default?receiveTimeout=100"
framework:
    messenger:
        transports:
            default:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
