db:
    type: mariadb:11.4
    disk: 2048
cacheredis:
    type: redis:7.2
    configuration:
        maxmemory_policy: volatile-lfu
sessionredis:
    type: redis-persistent:7.2
    disk: 1024
    configuration:
        maxmemory_policy: allkeys-lru
# comment if you want to disable rabbitmq

rabbitmq:
    type: rabbitmq:3.13
    disk: 1024
# uncomment if you want to use opensearch

#opensearch:
#    type: opensearch:2
#    disk: 256
# Change the disk space according to your needs for a.o. media files
fileshare:
    type: network-storage:2.0
    disk: 4096
